# Generated by Django 5.1.2 on 2024-10-21 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referral",
            options={"verbose_name": "Реферал", "verbose_name_plural": "Рефералы"},
        ),
    ]
